SELECT
	S.ID_SALARIO,
    S.ID_PESSOA,
    S.SALARIO,
    S.DATA_INICIO_VIGENCIA,
    S.DATA_FIM_VIGENCIA
FROM SALARIO S
INNER JOIN PESSOA P ON S.ID_PESSOA = P.ID_PESSOA
WHERE
	P.CPF = '123.123.123-12'
    AND S.DATA_FIM_VIGENCIA >= '2018-06-01';