CREATE TABLE `Teste`.`SALARIO` (
    `ID_SALARIO` INT NOT NULL AUTO_INCREMENT ,
    `ID_PESSOA` INT NOT NULL ,
    `SALARIO` FLOAT NOT NULL ,
    `DATA_INICIO_VIGENCIA` DATE NOT NULL ,
    `DATA_FIM_VIGENCIA` DATE NULL ,
     PRIMARY KEY (`ID_SALARIO`),
     FOREIGN KEY ( `ID_PESSOA` ) REFERENCES `PESSOA` ( `ID_PESSOA` ))
 ENGINE = InnoDB;

INSERT INTO `PESSOA` (`ID_PESSOA`, `CPF`, `NOME`) VALUES (NULL, '123.123.123-12', 'João da Silva');
INSERT INTO `PESSOA` (`ID_PESSOA`, `CPF`, `NOME`) VALUES (NULL, '456.456.456-01', 'José da Silva Júnior');